baseURL = '/'
languageCode = 'id-id'
title = 'Usaha Digital'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultTheme = "light"
  # Mengaktifkan Profil/Landing Mode
  [params.homeInfoParams]
    Title = "Usaha Digital - Partner Go Digital UMKM"
    Content = "Bikin Usaha Rapi, Rejeki Happy. Solusi IT praktis, ga pake ribet, khusus buat pejuang UMKM."

  [[params.socialIcons]]
    name = "whatsapp"
    url = "https://wa.me/628111047011" # Ganti dengan nomor asli
    
  [params.assets]
    disableHLJS = true
    
[menu]
  [[menu.main]]
    identifier = "layanan"
    name = "Paket Layanan"
    url = "/#layanan"
    weight = 10
